M48
; DRILL file {KiCad 8.0.4} date 2024-08-21T23:49:41-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-08-21T23:49:41-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X124.0Y-62.5
X124.0Y-102.5
X149.0Y-62.5
X149.0Y-102.5
M30
